### ISSUE TITLE
Implement filtering by date range

### ISSUE THREAD

**Issue by richarddli** [datawire/scout2csv#1]
A huge time saver would be supporting something like the following:

```
scout2csv --start-date=2017-01-01 --end-date=2018-01-01
```

in which case the data returned would only show the data associated with UUIDs created in that date range. Is this possible?

**Comment by plombardi89** [comment]
We can do it in an adhoc way via scout2csv using a conditional on the returned  data set but it will be very very slow (and getting slower as more records are written) or we can update the backend to make it possible to do efficient queries (see https://github.com/datawire/scout/issues/6)

I'm strongly recommending we update the backend to support better queries rather than continuing to hack stuff into this client.

**Comment by plombardi89** [comment]
Implemented in GH-2
